# Generated by Django 5.1.1 on 2024-10-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Stripe Product ID'),
        ),
    ]
