# Generated by Django 5.1.1 on 2024-10-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_product_stripe_product_id'),
        ('users', '0006_remove_user_payment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
