# Generated by Django 5.2 on 2025-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
    ]
