# Generated by Django 5.1.1 on 2024-10-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Plan'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subscription ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_made',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Payment made'),
        ),
    ]
