# Generated by Django 5.2 on 2025-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pix_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_accepted',
            field=models.BooleanField(default=False, verbose_name='Privacy Policy Accepted'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_accepted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Privacy Acceptance Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Terms and Conditions Accepted'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terms Acceptance Date'),
        ),
    ]
