# Generated by Django 5.1.1 on 2024-10-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_plan_name_remove_user_restricted_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
    ]
