# Generated by Django 5.1.1 on 2024-10-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AddField(
            model_name='user',
            name='next_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('R', 'Root'), ('M', 'Manager'), ('C', 'Collaborator')], max_length=1),
        ),
    ]
