# Generated by Django 5.1.1 on 2024-10-28 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1 Star(s)'), (2, '2 Star(s)'), (3, '3 Star(s)'), (4, '4 Star(s)'), (5, '5 Star(s)')], default=0, verbose_name='Rating')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comment')),
                ('category', models.CharField(choices=[('technical', 'Technical Issue'), ('improvement', 'Suggestion for Improvement'), ('praise', 'Praise')], max_length=20, verbose_name='Category')),
                ('feedback_mode', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10, verbose_name='Feedback Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
