# Generated by Django 5.1.1 on 2024-10-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('problema_tecnico', 'Problema Técnico'), ('sugestao_melhoria', 'Sugestão de Melhoria'), ('elogio', 'Elogio')], max_length=20, verbose_name='Category'),
        ),
    ]
