# Generated by Django 5.2 on 2025-04-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='active_landing_page',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Active Landing Page'),
        ),
    ]
