# Generated by Django 5.2 on 2025-04-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback_active_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
