# Generated by Django 5.2 on 2025-04-08 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Plano')),
                ('stripe_price_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Preço no Stripe')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('currency', models.CharField(default='usd', max_length=10, verbose_name='Moeda')),
                ('interval', models.CharField(help_text='Ex.: monthly, yearly', max_length=20, verbose_name='Intervalo de cobrança')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True, verbose_name='ID da Assinatura no Stripe')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('max_pcs', models.IntegerField(blank=True, default=0, null=True, verbose_name='Max PCs')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans_subscriptions.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
