# Generated by Django 5.1.1 on 2024-11-10 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Life Plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_plans', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='LifePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('receitas', 'Receitas'), ('estudos', 'Estudos'), ('custos', 'Custos'), ('lucro_prejuizo', 'Lucro/Prejuízo'), ('investimentos', 'Investimentos'), ('realizacoes', 'Realizações'), ('intercambio', 'Intercâmbio'), ('empresas', 'Empresas')], max_length=20, verbose_name='Category')),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('replicate_months', models.PositiveIntegerField(default=0, verbose_name='Replicate for X Months')),
                ('life_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='life_plan.lifeplan', verbose_name='Life Plan')),
            ],
        ),
    ]
