# Generated by Django 5.1.1 on 2024-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_plan', '0002_remove_lifeplanitem_replicate_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeplanitem',
            name='meta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Meta'),
        ),
    ]
